version: "3.2"

services:
  db:
    container_name: mysql
    image: mariadb
    hostname: mysql
    ports:
      - "3306:3306"
    networks:
      - dev
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: criteo
      MYSQL_PASSWORD: criteo
      MYSQL_DATABASE: config

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    hostname: zookeeper
    networks:
      dev:
        aliases:
          - zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      dev:
        aliases:
          - kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka_local
      KAFKA_CREATE_TOPICS: "view_product:1:1,show_banner:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    container_name: cassandra
    build: cassandra/
    image: criteo/cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    networks:
      - dev

networks:
  dev: