version: "3.2"

services:
  db:
    container_name: mysql
    image: mariadb
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - dev
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: criteo
      MYSQL_PASSWORD: criteo
      MYSQL_DATABASE: config

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
     - "2181:2181"
    networks:
      - dev

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    networks:
      - dev
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "view_product:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper

  cassandra:
    container_name: cassandra
    build: cassandra/
    image: criteo/cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    networks:
      - dev

networks:
  dev: