version: "3.2"

services:
  db:
    container_name: mysql
    image: mariadb
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - dev
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: criteo
      MYSQL_PASSWORD: criteo
      MYSQL_DATABASE: config

  kafka:
    container_name: kafka-zookeeper
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    networks:
      - dev
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      CONSUMER_THREADS: 1
      TOPICS: "view_product,show_banner"

  cassandra:
    container_name: cassandra
    build: cassandra/
    image: criteo/cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    networks:
      - dev

networks:
  dev: