spring:
  kafka:
    bootstrap-servers: "kafka:9092"
    consumer:
      group-id: "foo"
      auto-offset-reset: "earliest"

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

kafka:
  topic:
    view-product: view_product